// <auto-generated />
namespace Thinktecture.IdentityServer.Core.Repositories.Migrations.SqlServer
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSitefinity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSitefinity));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161420585_AddSitefinity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
